#!/usr/bin/env python3
"""Regenerate the AUTO:relations / AUTO:family blocks from stored edges.

Reads `parents` (on each child) + `partners` and computes children, siblings,
and each family's child set. Rewrites ONLY the marked AUTO blocks; never touches
your prose. Run after any edit:

    python scripts/regenerate.py
"""
from __future__ import annotations
import re
from common import ROOT, load_people, family_files, split_frontmatter, partner_slugs, link

REL_RE = re.compile(
    r"<!-- AUTO:relations.*?-->.*?<!-- /AUTO -->", re.DOTALL)
FAM_RE = re.compile(
    r"<!-- AUTO:family.*?-->.*?<!-- /AUTO -->", re.DOTALL)


def build_indexes(people):
    children = {s: [] for s in people}      # parent slug -> [child slug]
    for slug, rec in people.items():
        for parent in rec["fm"].get("parents") or []:
            children.setdefault(parent, []).append(slug)
    return children


def siblings_of(slug, people):
    my_parents = set(people[slug]["fm"].get("parents") or [])
    if not my_parents:
        return []
    sibs = []
    for other, rec in people.items():
        if other == slug:
            continue
        if my_parents & set(rec["fm"].get("parents") or []):
            sibs.append(other)
    return sorted(sibs)


def fmt_list(slugs, people):
    return ", ".join(link(s, people) for s in slugs) if slugs else "_none recorded_"


def relations_block(slug, people, children):
    fm = people[slug]["fm"]
    parents = fm.get("parents") or []
    partners = partner_slugs(fm)
    kids = sorted(children.get(slug, []))
    sibs = siblings_of(slug, people)
    lines = [
        "<!-- AUTO:relations — regenerated by scripts/regenerate.py, do not edit by hand -->",
        "## Relations",
        f"- **Parents:** {fmt_list(parents, people)}",
        f"- **Partners:** {fmt_list(partners, people)}",
        f"- **Children:** {fmt_list(kids, people)}",
        f"- **Siblings:** {fmt_list(sibs, people)}",
        "<!-- /AUTO -->",
    ]
    return "\n".join(lines)


def family_block(fm, people):
    union = set(fm.get("partners") or [])
    kids = sorted(
        s for s, rec in people.items()
        if set(rec["fm"].get("parents") or []) == union and union
    )
    lines = [
        "<!-- AUTO:family — regenerated by scripts/regenerate.py, do not edit by hand -->",
        "## Children of this union",
        fmt_list(kids, people) if kids else "_none recorded_",
        "<!-- /AUTO -->",
    ]
    return "\n".join(lines)


def main():
    people = load_people()
    children = build_indexes(people)

    changed = 0
    for slug, rec in people.items():
        block = relations_block(slug, people, children)
        text = rec["path"].read_text(encoding="utf-8")
        new = REL_RE.sub(lambda _: block, text) if REL_RE.search(text) else text.rstrip() + "\n\n" + block + "\n"
        if new != text:
            rec["path"].write_text(new, encoding="utf-8")
            changed += 1

    for slug, path in family_files():
        fm, _ = split_frontmatter(path.read_text(encoding="utf-8"))
        block = family_block(fm, people)
        text = path.read_text(encoding="utf-8")
        new = FAM_RE.sub(lambda _: block, text) if FAM_RE.search(text) else text.rstrip() + "\n\n" + block + "\n"
        if new != text:
            path.write_text(new, encoding="utf-8")
            changed += 1

    print(f"regenerate: {len(people)} people scanned, {changed} file(s) updated.")


if __name__ == "__main__":
    main()
